name: Build and Push Docker Image to Docker Hub

on:
  release:
    types: [published]
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login, Build, Tag & Push Action
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          # Username to connect to Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password to connect to Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Docker build context
          context: .
          # Docker build file
          file: Dockerfile
          # Docker repository owner
          repoOwner: ${{ secrets.DOCKER_USERNAME }}
          # Docker repository
          repository: ${{ github.repository }}
          # Docker image tag
          tag: latest
          # Registry you want to push the Docker image
          # registry: # optional
          
